permalink: pretty

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "less", "node_modules", "Gruntfile.js", "package.json"]

highlighter: "pygments"

title: Better Pixels
description: Coding Notes by Daniele Zanni

header-img: img/home-bg.jpg
default-img: img/header.png

email: info@betterpixels.co.uk

twitter_username: syymza
github_username:  syymza
facebook_username:  danielezanni

url: http://www.betterpixels.co.uk

markdown: kramdown

paginate: 5